services:
  - name: gemini-backend
    type: web
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      RENDER_PYTHON_VERSION: "3.10.0"
    plan: free
